enum ToDoConstants {
    TODO_CREATE,
    TODO_COMPLETE,
    TODO_DESTROY,
    TODO_DESTROY_COMPLETED,
    TODO_TOGGLE_COMPLETE,
    TODO_UNDO_COMPLETE,
    TODO_UPDATE_TEXT
}

export = ToDoConstants;